# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-galaxy" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/go-galaxy"]
    end
  end

  version "1.4.0"

  on_macos do
    on_arm do
      sha256 "77574a0333633df0091ad0b7a692da424a929efb32b991dc0f1284d716da3142"
      url "https://github.com/greeddj/go-galaxy/releases/download/v#{version}/go-galaxy_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5ff8a81988c91014dc496b2b82bee7ff06ecd3a19a367877fbf49fa7f52f2553"
      url "https://github.com/greeddj/go-galaxy/releases/download/v#{version}/go-galaxy_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e69f754e5e09f0b2d73de07816437016a5c3fa3e7f16ef7818732673c9d5028a"
      url "https://github.com/greeddj/go-galaxy/releases/download/v#{version}/go-galaxy_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d22e049243698773efd2c7febc1b14a38a5c5f17e1a2b93e327ed52708735925"
      url "https://github.com/greeddj/go-galaxy/releases/download/v#{version}/go-galaxy_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "go-galaxy"
  desc "Fast Ansible Galaxy collections and roles installer for CI."
  homepage "https://github.com/greeddj/go-galaxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-galaxy"

  # No zap stanza required

  caveats <<~EOS
    These builds are not Apple-notarized, so this cask clears the macOS
    quarantine attribute from the binary it installs. That skips a Gatekeeper
    check on your behalf. To verify the download instead, see
    https://github.com/greeddj/go-galaxy/blob/v1.4.0/docs/guides/security.md#verifying-a-release
  EOS
end
