# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-galaxy" do
  name "go-galaxy"
  desc "Fast Ansible Galaxy collections installer for CI."
  homepage "https://github.com/greeddj/go-galaxy"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-galaxy"

  on_macos do
    on_intel do
      url "https://github.com/greeddj/go-galaxy/releases/download/v#{version}/go-galaxy_#{version}_Darwin_x86_64.tar.gz"
      sha256 "e794a71e7d86caffccd7a93595b12a32033fcf675b4179492d1bea7af76de7db"
    end
    on_arm do
      url "https://github.com/greeddj/go-galaxy/releases/download/v#{version}/go-galaxy_#{version}_Darwin_arm64.tar.gz"
      sha256 "39ecd3ba901d6b168e47264abffda19dc7fcdf43eec4148377f6ba74b3a157ab"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/greeddj/go-galaxy/releases/download/v#{version}/go-galaxy_#{version}_Linux_x86_64.tar.gz"
      sha256 "cc90ffe0a03d06bf2adb10c6b4d1d6b1f62f46849efcd9f5fe0d49d92c948b83"
    end
    on_arm do
      url "https://github.com/greeddj/go-galaxy/releases/download/v#{version}/go-galaxy_#{version}_Linux_arm64.tar.gz"
      sha256 "38e257f385c916566a64b1d3cb3488a810225836acd2aa0a745cf9757d15441d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-galaxy"]
    end
  end

  # No zap stanza required
end
