# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-galaxy" do
  name "go-galaxy"
  desc "Fast Ansible Galaxy collections installer for CI."
  homepage "https://github.com/greeddj/go-galaxy"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dist/go-galaxy"

  on_macos do
    on_intel do
      url "https://github.com/greeddj/go-galaxy/releases/download/v#{version}/go-galaxy_#{version}_Darwin_x86_64.tar.gz"
      sha256 "8de2fa89de3dd761878c8dee9438242159bb684584fd52cd10de1fc57a2e93e4"
    end
    on_arm do
      url "https://github.com/greeddj/go-galaxy/releases/download/v#{version}/go-galaxy_#{version}_Darwin_arm64.tar.gz"
      sha256 "e891d7fa28f510b77bcf84d3afde6c1f3a87f6f0fed58ae9fbba2dc2e77a1acb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/greeddj/go-galaxy/releases/download/v#{version}/go-galaxy_#{version}_Linux_x86_64.tar.gz"
      sha256 "e8b10c41f487aa6b7c509cf80074cdc64967ce9e4710c67e414dd5395db7b8af"
    end
    on_arm do
      url "https://github.com/greeddj/go-galaxy/releases/download/v#{version}/go-galaxy_#{version}_Linux_arm64.tar.gz"
      sha256 "f8a143814f7e3097f919901d86495449407e6681258b40f6178214efb9e5e3fe"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dist/go-galaxy"]
    end
  end

  # No zap stanza required
end
