# This file was generated by GoReleaser. DO NOT EDIT.
cask "imapsync-go" do
  name "imapsync-go"
  desc "IMAP to IMAP synchronization tool"
  homepage "https://github.com/greeddj/imapsync-go"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "imapsync-go"

  on_macos do
    on_intel do
      url "https://github.com/greeddj/imapsync-go/releases/download/v#{version}/imapsync-go_#{version}_Darwin_x86_64.tar.gz"
      sha256 "9964fa48b97ae0203362c879a71976a8350a43a2a470c07fd9f10985738987da"
    end
    on_arm do
      url "https://github.com/greeddj/imapsync-go/releases/download/v#{version}/imapsync-go_#{version}_Darwin_arm64.tar.gz"
      sha256 "925f223f862a73fdf443949cd0af71f0b1f6b582b3286d129e031edd288528b3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/greeddj/imapsync-go/releases/download/v#{version}/imapsync-go_#{version}_Linux_x86_64.tar.gz"
      sha256 "4aa3ae755075455cac875be838b9bb882f902103abcd69ff42129e2d2e6c5ed5"
    end
    on_arm do
      url "https://github.com/greeddj/imapsync-go/releases/download/v#{version}/imapsync-go_#{version}_Linux_arm64.tar.gz"
      sha256 "716c719f2f856f4882e036f432d5350533b8e839a4d1b4a11c1b5b29486094c3"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/imapsync-go"]
    end
  end

  # No zap stanza required
end
