# This file was generated by GoReleaser. DO NOT EDIT.
cask "imapsync-go" do
  name "imapsync-go"
  desc "IMAP to IMAP synchronization tool"
  homepage "https://github.com/greeddj/imapsync-go"
  version "1.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "imapsync-go"

  on_macos do
    on_intel do
      url "https://github.com/greeddj/imapsync-go/releases/download/v#{version}/imapsync-go_#{version}_Darwin_x86_64.tar.gz"
      sha256 "ede1cd442f6d749bfe2ee533fdcd6db827ad4e505e7a26abe5db9d0590ea8dc0"
    end
    on_arm do
      url "https://github.com/greeddj/imapsync-go/releases/download/v#{version}/imapsync-go_#{version}_Darwin_arm64.tar.gz"
      sha256 "fcd3bbc8b2a2d32f8c58cb8964e13f9d2a8f04d1f4cc5939d83f6082de294e23"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/greeddj/imapsync-go/releases/download/v#{version}/imapsync-go_#{version}_Linux_x86_64.tar.gz"
      sha256 "e3a4e8537c5d3c1c3263af01bc1fb08e338e944975574e4f3c048105fd657f3d"
    end
    on_arm do
      url "https://github.com/greeddj/imapsync-go/releases/download/v#{version}/imapsync-go_#{version}_Linux_arm64.tar.gz"
      sha256 "72f286e6ae484b6652ffa492bebaf4fd105bb141e0e30ec6ad7ba3a718f8b928"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/imapsync-go"]
    end
  end

  # No zap stanza required
end
