# This file was generated by GoReleaser. DO NOT EDIT.
cask "ys" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "bbb1a6c3de7e8e52a0038171cc5d5f6e0cd5bafdd3170885030d64147a90be46"
      url "https://github.com/greeddj/ys/releases/download/v#{version}/ys_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d0df83194460c56a469338c2d280d69fac0d254a83aef3748689879d60f74fa7"
      url "https://github.com/greeddj/ys/releases/download/v#{version}/ys_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "511fe3445d5dca9245ea9fb64467cc3afad95adedb14f8723116ed0b3c71c99a"
      url "https://github.com/greeddj/ys/releases/download/v#{version}/ys_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "575c29a52987118cd847de75647b6eeb74a2d0e36323b0259370fa31708e9b3b"
      url "https://github.com/greeddj/ys/releases/download/v#{version}/ys_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "ys"
  desc "Search YAML files for a key and group identical results across files"
  homepage "https://github.com/greeddj/ys"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ys"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ys"]
    end
  end

  # No zap stanza required

end
