# This file was generated by GoReleaser. DO NOT EDIT.
cask "ys" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/ys"]
    end
  end

  version "1.2.1"

  on_macos do
    on_arm do
      sha256 "34ea2aea784d266e2f7228e2f17e5cb059d28288de8290825c8224fe4bc7ede3"
      url "https://github.com/greeddj/ys/releases/download/v#{version}/ys_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "187034526de2534b47e8ced974c880baed09fc395a01beca27585fb4eb380914"
      url "https://github.com/greeddj/ys/releases/download/v#{version}/ys_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "04f9aeec6717cc3da3e159a74ace29b7c75cb4ac08fdf9c1a058abe8e2eecd59"
      url "https://github.com/greeddj/ys/releases/download/v#{version}/ys_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4888d10dddcd73fce6c7b1b105a1badcd34937521a425e57e0ac3b50d46d2ffa"
      url "https://github.com/greeddj/ys/releases/download/v#{version}/ys_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "ys"
  desc "Search YAML files for a key and group identical results across files"
  homepage "https://github.com/greeddj/ys"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ys"

  # No zap stanza required
end
