# This file was generated by GoReleaser. DO NOT EDIT.
cask "ys" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "238f5f852f5ac53c3a2c63b75097f7e35dd37a1ca374de239406f4e8a6f3dc47"
      url "https://github.com/greeddj/ys/releases/download/v#{version}/ys_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7350a27ce2e9a0c1356e95b3a899c3ca7d6061ecdc61dab3cb9141f4a4990325"
      url "https://github.com/greeddj/ys/releases/download/v#{version}/ys_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d87bd32b6bd44e6a7b2a11dcb144658311594bfe8ad75b93e6b64a2922f9ce5d"
      url "https://github.com/greeddj/ys/releases/download/v#{version}/ys_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3d5fe929caa46da2735ea1311e760f55dfec3cc27e67c369f41bf2bbcf1adf3b"
      url "https://github.com/greeddj/ys/releases/download/v#{version}/ys_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "ys"
  desc "Search YAML files for a key and group identical results across files"
  homepage "https://github.com/greeddj/ys"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ys"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ys"]
    end
  end

  # No zap stanza required

end
